### ISSUE TITLE
Can't commit without pulling other's changes

### ISSUE THREAD

**Issue by stgm** [software-engineering-amsterdam/sea-of-ql#1]
Every time I want to push I have to pull in your changes. This results in a merge which is trivial, but complicates the repo history. Anyone know how to do this cleanly?

**Comment by kevinvandervlist** [comment]
http://www.kernel.org/pub/software/scm/git/docs/git-merge.html

-> Fast-forward Merge?

**Comment by martyn82** [comment]
This is normal behavior of Git if working in one branch. What you can do, is create a branch locally, work in there, and when finished, you checkout master, pull changes, merge your branch, and push.

**Comment by stgm** [comment]
Fast-forward werkte niet. Dat is ook de default volgens `man git-merge` dus dat had ook vanzelf moeten gaan maar lukt om een of andere reden niet.

**Comment by tvdstorm** [comment]
I think this is normal too. Let's not experiment too much with git ;-)
