### ISSUE TITLE
Boolean connectives in JACC grammar and Lexer

### ISSUE THREAD

**Issue by tvdstorm** [software-engineering-amsterdam/sea-of-ql#2]
Unfortunately there was a bug in the prototype code I provided (thanks @LE-Blythe for reporting). In the prototype dir this has been fixed now in commit .

How to update your code:

``` yacc
%token '*' '/' '+' '-' OR AND NEQ EQ '<' LEQ '>' GEQ '!'
```

(NEQ wasn't there)

Introduce relops into the precedence hierarchy.

``` yacc
%left '>' '<' GEQ LEQ NEQ EQ
```

Change start non-terminal to `expr`:

``` yacc
 top : expr { result = $1; }
     ;
```

Add the relops to the normal expression production rule:

``` yacc
         | expr EQ expr         { $$ = new Eq($1, $3); }
         | expr NEQ expr        { $$ = new NEq($1, $3); }
         | expr '>' expr        { $$ = new GT($1, $3); }
         | expr '<' expr        { $$ = new LT($1, $3); }
         | expr GEQ expr        { $$ = new GEq($1, $3); }
         | expr LEQ expr        { $$ = new LEq($1, $3); }
```

Change the bracket production from `'(' comp ')'` to `'(' expr ')'`. See the protoype dir to see the complete result.

In the lexer, the problem is solved as follows:

``` java
if  (c == '&') {
   nextChar(); // <----- was missing
   return token = AND;
}
```

Same in the case of recognizing `||`.

**Comment by madmus** [comment]
Same for ==
