### ISSUE TITLE
Sample assertions are reversed

### ISSUE THREAD

**Issue by stgm** [software-engineering-amsterdam/sea-of-ql#5]
Just a warning. Tijs provided some sample tests in `TestExpressions.java`. He reversed the arguments to `assertEquals` though. Here's the function signature:

```
public static void assertEquals(java.lang.Object expected, java.lang.Object actual)
```

Expected value first, actual value second. This is actually important because of the way JUnit articulates its test output.

**Comment by tvdstorm** [comment]
Yes. I noticed it too. Good catch. Please change the order in the tests and use the correct order in your own.
