### ISSUE TITLE
sea-of-ql git statistics

### ISSUE THREAD

**Issue by kevinvandervlist** [software-engineering-amsterdam/sea-of-ql#6]
Regarding the statistics that were attached to the email @tvdstorm sent (courtesy @stgm ), I googled for another statistics generator. I came across [git_stats](https://github.com/tomgi/git_stats), and put an instance online for the stats of sea-of-ql. It can be found [here](http://kevinvandervlist.nl/SC/stats/general.html) and will be updated every night at 2.30.

**Comment by tvdstorm** [comment]
Very nice! Thanks @kevinvandervlist. I'm going to do this every year :+1:

**Comment by stgm** [comment]
You can close this ticket now, it's still on my GitHub homepage ;-)

**Comment by kevinvandervlist** [comment]
Whoops, here you go
